"""empty message

Revision ID: 71766a979145
Revises: 
Create Date: 2023-10-02 23:56:40.591886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71766a979145'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_resources',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.Enum('Database', 'Table', 'System', name='resource_type'), nullable=False),
    sa.Column('resource_comment', mysql.CHAR(length=100), nullable=True),
    sa.Column('system_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('database_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['db_resources.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['system_id'], ['db_resources.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_directories',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('system_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('db_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('table_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('entry_name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('entry_length', sa.INTEGER(), nullable=False),
    sa.Column('entry_type', mysql.CHAR(length=100), nullable=True),
    sa.Column('entry_name_chn', mysql.CHAR(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_id'], ['db_resources.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['system_id'], ['db_resources.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['table_id'], ['db_resources.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_directories')
    op.drop_table('db_resources')
    # ### end Alembic commands ###
